//
//  PlayerViewController.swift
//  OnlineRadio
//
//  Created Артём Балашов on 19/01/2019.
//  Copyright © 2019 Артём Балашов. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//  https://github.com/Banck/Swift-viper-template-for-xcode
//

import UIKit

class PlayerViewController: UIViewController {
    // MARK: - Properties
	var presenter: PlayerPresenterInterface?
    @IBOutlet weak var playPauseButton: UIButton!
    @IBOutlet weak var stationNameLabel: UILabel!
    @IBOutlet weak var stationImageView: UIImageView!
    
    // MARK: - Lifecycle -
	override func viewDidLoad() {
        super.viewDidLoad()
        presenter?.viewDidLoad()
    }

}

//MARK: - Actions
extension PlayerViewController {
    @IBAction func didSelectPlayPauseButtton(_ sender: UIButton) {
        presenter?.didSelectPlayPauseButton()
    }
}

// MARK: - PlayerView
extension PlayerViewController: PlayerView {
    func displayButtonImage(_ image: UIImage) {
        playPauseButton.setImage(image, for: .normal)
        playPauseButton.setImage(image, for: .highlighted)
    }
    
    func displayStationName(_ stationName: String) {
       stationNameLabel.text = stationName
    }
    
    func displaySongName(_ songName: String) {
        
    }
    
    func displayImage(_ image: UIImage) {
        stationImageView.image = image
    }
    
    
}
