//
//  PlayerConfigurator.swift
//  OnlineRadio
//
//  Created Артём Балашов on 19/01/2019.
//  Copyright © 2019 Артём Балашов. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//  https://github.com/Banck/Swift-viper-template-for-xcode
//

import UIKit

struct PlayerConfigurator {

    static func createModule(with stationID: Int) -> UIViewController {
        var view: PlayerViewController!

        let viewController = UIStoryboard.init(name: "Player", bundle: Bundle.main).instantiateInitialViewController()
        if viewController == nil {
            fatalError("Seems there is no initial view controller in Player.storyboard")
        }

        if viewController is UINavigationController {
            view = (viewController as! UINavigationController).viewControllers.first as! PlayerViewController
        } else {
            view = viewController as! PlayerViewController
        }

        let interactor = PlayerInteractor()
        let router = PlayerRouter()
        let presenter = PlayerPresenter(interface: view, interactor: interactor, router: router, stationID: stationID)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return viewController!
    }
}
