//
//  PlayerRouter.swift
//  OnlineRadio
//
//  Created Артём Балашов on 19/01/2019.
//  Copyright © 2019 Артём Балашов. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//  https://github.com/Banck/Swift-viper-template-for-xcode
//

import UIKit

class PlayerRouter {
    // MARK: - Properties
    weak var viewController: UIViewController?
}

// MARK: - PlayerWireframeInterface -
extension PlayerRouter: PlayerWireframeInterface {
    
    func navigate(to option: PlayerNavigationOption) {
//        switch option {
//        case .firstModule:
//              openFirstModule()
//        case .secondModule(let someData):
        //      openSecondModule(with someData)
//        }
    }
}
